name: '"Perx AWS ECS Deploy" for GitHub Actions'
description: Deploy new builds to AWS ECS, designed for use within Perx Health infrastructure
branding:
  icon: upload-cloud
  color: blue
inputs:
  aws-access-key-id:
    description: AWS_ACCESS_KEY_ID used to invoke AWS services
    required: true
  aws-secret-access-key:
    description: AWS_SECRET_ACCESS_KEY used to invoke AWS services
    required: true
  perx-env:
    type: choice
    description: Nominate the environment in which we're deploying
    required: true
    options:
      - dev
      - qa
      - demo
      - staging
      - prod
  perx-region:
    type: choice
    description: Nominate the region in which we're deploying
    required: true
    options:
      - au
      - us
  perx-app-name:
    description: Unique name of the application which partially forms the ECS task name, amongst other attributes
    required: true
  task-definition:
    description: Path on disk where your ECS Task Definition .tpl.json file can be found
    required: true
  image-tag:
    description: Nominate name with which the image is tagged
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.perx-env }}
    - ${{ inputs.perx-region }}
    - ${{ inputs.perx-app-name }}
    - ${{ inputs.task-definition }}
    - ${{ inputs.image-tag }}
