name: '"Perx AWS ECS Deploy" for GitHub Actions'
description: Deploy new builds to AWS ECS, designed for use within Perx Health infrastructure

branding:
  icon: upload-cloud
  color: blue

inputs:
  perx_env:
    type: choice
    description: Nominate the environment in which we're deploying
    required: true
    options:
      - dev
      - qa
      - demo
      - staging
      - prod
  perx_region:
    type: choice
    description: Nominate the region in which we're deploying
    required: true
    options:
      - au
      - us
  perx_app_name:
    description: Unique name of the application which partially forms the ECS task name, amongst other attributes
    required: true
  task_definition:
    description: Path on disk where your ECS Task Definition .tpl.json file can be found
    required: true
  image_tag:
    description: Nominate name with which the image is tagged
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.perx_env }}
    - ${{ inputs.perx_region }}
    - ${{ inputs.perx_app_name }}
    - ${{ inputs.task_definition }}
    - ${{ inputs.image_tag }}
